language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements/requirements.txt
script:
- pytest
deploy:
  - provider: pypi
    user: "__token__"
    password:
      secure: "VxEiJbIz784PAEbixdlOmEaE4vNIvct3/roGlYfe2n8ghZLny5hprvDrXXMK+HlZgPvN9v/8xuXElxHNTRRVrOUMlReReqzwsh58Jxfh4ge3ID9IkdA+5/fYLPGR/sohUcNiBdHJVCuzrPOwR2eji8LFwRe9IA7vxBAKOscmcME9PBcSWyPVTzfMkBgvZpW8AUWRcUYo8hLXpm17G+AI5MUoMnugaRa9BNcQVTIh8rE2n3E1RNhP6rLQqW5gOKCmGWWiLuI7MGP1nexQqmKrcSMj4MFHaVWLrZUBtJ/oQEi/ztBVzNABtGQe25kcLSnvjLYJ54Ujp4od75s1zUCR6RP+bLvKkzhorZAk5+MnaDBnWypcsDPFbPNKYgl5SjscXtV6F5VAPKbjAv/SX9MdDQqUUgHNAACnx492XiNJW9ZxEPYJFo/R5og1Gr3a4h7FZ1iCM3Uw9MMlijPX6o8J6fvbLARvBpTSiZ0GBMzM/6Sdo9utUrvGZrKxOX2Fivn6XA1coIhV6w3D/fr/O7nJmVOUSsxtig51H6wb98V4kxq1onjxI6d667buJa3rC0r4cMf9ffYb13RBuC2SbQkMLCGNERtRIUjY2SLq0FBP0BqMMGI1d38PtqD7qbqe5+nZJjYOPh7Th4mBkCW6Q0ArvTy52H+KA+f95RsSJ1peXrY="
    server: https://test.pypi.org/legacy/
    skip_existing: true
    on:
      branch: staging